# This file is the description of the installation and tests pipeline
# It is meant to be configuration agnostic
---
############################################
############ Pipeline defaults #############
############################################

# Common variables and scripts
include:
  local: '/.gitlab/ci/global.yml'

# Explicit stage definition
stages:
  - Installation
  - Basic Testing
  - Regular Testing
  - Applications
  - Benchmarks
  - Extended Network Testing
  - Extended Threads Testing
  - Additional Testing

# Default variables
variables:
  # PCVS Basic run command
  PCVS_RUN: pcvs -v run --override --profile-path ${GL_PIPELINE_PATH}/mpc_ci/utils/profile/mpc.yml
  # PCVS Common command used
  PCVS_COMMAND: ${PCVS_RUN} --print errors -S
  # PCVS Command used to print benchmarks results
  PCVS_COMMAND_BENCH: ${PCVS_RUN} --print all -S
  # MPC CI job specific path
  CI_PCVS_DIR: '$GL_LOCAL_BUILD_DIR/step_$(echo "$CI_JOB_NAME" | sed -e "s/ /_/g")/"'


############################################
############## Installation ################
############################################

.configuration_commands:
  before_script:
    - echo "${GL_LOCAL_BUILD_DIR}"
    - echo "${GL_LOCAL_INSTALL_DIR}"
    - rm -rf ${GL_LOCAL_BUILD_DIR} ${GL_LOCAL_INSTALL_DIR}
    - mkdir ${GL_LOCAL_BUILD_DIR} && cd ${GL_LOCAL_BUILD_DIR}
    - module load pmix gnu/13.3.0
  script:
    - ${CI_PROJECT_DIR}/installmpc -vv --prefix=${GL_LOCAL_INSTALL_DIR} ${GL_INSTALL_OPTS}

Installation:
  stage: 'Installation'
  needs: []
  extends: ['.configuration_commands']


############################################
############## Simple testing ##############
############################################

.load_mpc:
  before_script:
    - module load pmix gnu/13.3.0
    - source ${GL_LOCAL_INSTALL_DIR}/mpcvars.sh
    - echo "MPC loaded from ${GL_LOCAL_INSTALL_DIR}/mpcvars.sh"
    # Sanity check
    - mpc_cc --help && mpcrun --help

.prepare_mpc_ci:
  before_script:
    - test -d "${CI_PCVS_DIR}" || mkdir -p "${CI_PCVS_DIR}"
    - cd "${CI_PCVS_DIR}"
    - echo "Step run from ${CI_PCVS_DIR}"
  rules:
    - if: $DO_REGULAR_TESTING == true

.load_run_deps:
  before_script:
    - !reference [.load_pcvs, before_script]
    - !reference [.load_mpc, before_script]

Simple Run:
  stage: 'Basic Testing'
  needs: ['Installation']
  extends: ['.load_run_deps', '.prepare_mpc_ci']
  script:
    - ${PCVS_COMMAND} "${GL_MPC_CI_PATH}/trivial"


############################################
############ Additional testing ############
############################################

Privatization:
  stage: 'Additional Testing'
  needs: ['Installation']
  extends: ['.load_run_deps']
  variables:
    REPRODUCERS_PATH: '${GL_MPC_CI_PATH}/reproducers'
  before_script:
    - !reference [.prepare_mpc_ci, before_script]
  script:
    - ${PCVS_COMMAND} "${GL_MPC_CI_PATH}/privatization/" "${REPRODUCERS_PATH}/privatization"
  rules:
    - if: $HAS_PRIVATIZATION == true && $DO_REGULAR_TESTING == true

Reproducers:
  stage: 'Additional Testing'
  needs: ['Installation']
  extends: ['.load_run_deps', '.prepare_mpc_ci']
  variables:
    REPRODUCERS_PATH: '${GL_MPC_CI_PATH}/reproducers'
  script:
    - ${PCVS_COMMAND} "${REPRODUCERS_PATH}/basics" "${REPRODUCERS_PATH}/lowcomm" "${REPRODUCERS_PATH}/MPI"


############################################
############# Regular testing ##############
############################################

Lowcomm:
  stage: 'Regular Testing'
  needs: ['Simple Run']
  extends: ['.load_run_deps', '.prepare_mpc_ci']
  script:
    - ${PCVS_COMMAND} "${GL_MPC_CI_PATH}/lowcomm/"

MPI Simple C:
  stage: 'Regular Testing'
  needs: ['Simple Run']
  extends: ['.load_run_deps', '.prepare_mpc_ci']
  script:
    - ${PCVS_COMMAND} "${GL_MPC_CI_PATH}/MPI/simple/c"

MPI Simple Fortran:
  stage: 'Regular Testing'
  needs: ['Simple Run']
  extends: ['.load_run_deps', '.prepare_mpc_ci']
  script:
    - ${PCVS_COMMAND} "${GL_MPC_CI_PATH}/MPI/simple/fortran"

OpenMP Tasking Examples:
  stage: 'Regular Testing'
  needs: ['Simple Run']
  extends: ['.load_run_deps', '.prepare_mpc_ci']
  script:
    - ${PCVS_COMMAND} "${GL_MPC_CI_PATH}/OpenMP/task/examples"

OpenMP Tasking Cholesky:
  stage: 'Regular Testing'
  needs: ['Simple Run']
  extends: ['.load_run_deps', '.prepare_mpc_ci']
  script:
    - ${PCVS_COMMAND} "${GL_MPC_CI_PATH}/OpenMP/task/cholesky"


############################################
############## Applications ################
############################################

MPI NAS-MZ:
  stage: 'Applications'
  needs: ['Lowcomm', 'MPI Simple C', 'MPI Simple Fortran']
  extends: ['.load_run_deps', '.prepare_mpc_ci']
  script:
    - ${PCVS_COMMAND} "${GL_MPC_CI_PATH}/hybrid/NAS/MZ-MPI"

Lulesh:
  stage: 'Applications'
  needs: ['Lowcomm', 'MPI Simple C', 'MPI Simple Fortran', 'OpenMP Tasking Examples', 'OpenMP Tasking Cholesky']
  extends: ['.load_run_deps', '.prepare_mpc_ci']
  script:
    - ${PCVS_COMMAND} "${GL_MPC_CI_PATH}/corals/lulesh-2.0.3"

MiniFE:
  stage: 'Applications'
  needs: ['Lowcomm', 'MPI Simple C', 'MPI Simple Fortran', 'OpenMP Tasking Examples', 'OpenMP Tasking Cholesky']
  extends: ['.load_run_deps', '.prepare_mpc_ci']
  script:
    - ${PCVS_COMMAND} "${GL_MPC_CI_PATH}/corals/miniFe"

OpenMP NAS-MZ:
  stage: 'Applications'
  needs: ['OpenMP Tasking Examples', 'OpenMP Tasking Cholesky']
  extends: ['.load_run_deps', '.prepare_mpc_ci']
  script:
    - ${PCVS_COMMAND} "${GL_MPC_CI_PATH}/hybrid/NAS/MZ-OMP"


############################################
################ Benchmarks ################
############################################

MPI IMB-MPI 2017:
  stage: 'Benchmarks'
  needs: ['Lowcomm', 'MPI Simple C', 'MPI Simple Fortran']
  extends: ['.load_run_deps', '.prepare_mpc_ci']
  script:
    - ${PCVS_COMMAND} "${GL_MPC_CI_PATH}/MPI/IMB_2017/check-mpi/"

MPI IMB-NBC 2017:
  stage: 'Benchmarks'
  needs: ['Lowcomm', 'MPI Simple C', 'MPI Simple Fortran']
  extends: ['.load_run_deps', '.prepare_mpc_ci']
  script:
    - ${PCVS_COMMAND} "${GL_MPC_CI_PATH}/MPI/IMB_2017/check-nbc/"

MPI NBC:
  stage: 'Benchmarks'
  needs: ['Lowcomm', 'MPI Simple C', 'MPI Simple Fortran']
  extends: ['.load_run_deps', '.prepare_mpc_ci']
  script:
    - ${PCVS_COMMAND} "${GL_MPC_CI_PATH}/MPI/NBC"


############################################
############## Extended Tests ##############
############################################

.prepare_pcvs_benchmark:
  before_script:
    - test -d "${CI_PCVS_DIR}" || mkdir -p "${CI_PCVS_DIR}"
    - cd "${CI_PCVS_DIR}"
    - echo "Step run from ${CI_PCVS_DIR}"
  rules:
    - if: '$EXTENDED == "true"'


# Testing
## MPI
Intel ANL:
  stage: 'Extended Network Testing'
  needs: ['Lowcomm', 'MPI Simple C', 'MPI Simple Fortran']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - ${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/MPI/Intel_ANL"

MPI IO:
  stage: 'Extended Network Testing'
  needs: ['Lowcomm', 'MPI Simple C', 'MPI Simple Fortran']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - ${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/MPI/MPI-IO"

MPI NAS:
  stage: 'Extended Network Testing'
  needs: ['Lowcomm', 'MPI Simple C', 'MPI Simple Fortran']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - ${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/MPI/NAS"

MPICH:
  stage: 'Extended Network Testing'
  needs: ['Lowcomm', 'MPI Simple C', 'MPI Simple Fortran']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - ${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/MPI/mpich-3.4.2"

PARCO:
  stage: 'Extended Network Testing'
  needs: ['Lowcomm', 'MPI Simple C', 'MPI Simple Fortran']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - ${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/MPI/Threading"


## OpenMP
OpenMP BOTS:
  stage: 'Extended Threads Testing'
  needs: ['OpenMP Tasking Examples', 'OpenMP Tasking Cholesky']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - ${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/OpenMP/BOTS"

CLOMP:
  stage: 'Extended Threads Testing'
  needs: ['OpenMP Tasking Examples', 'OpenMP Tasking Cholesky']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - ${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/OpenMP/CLOMP"

EPCC:
  stage: 'Extended Threads Testing'
  needs: ['OpenMP Tasking Examples', 'OpenMP Tasking Cholesky']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - ${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/OpenMP/EPCC"

GOMP:
  stage: 'Extended Threads Testing'
  needs: ['OpenMP Tasking Examples', 'OpenMP Tasking Cholesky']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - ${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/OpenMP/GOMP"

OpenMP NAS:
  stage: 'Extended Threads Testing'
  needs: ['OpenMP Tasking Examples', 'OpenMP Tasking Cholesky']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - ${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/OpenMP/NAS"

OpenUH:
  stage: 'Extended Threads Testing'
  needs: ['OpenMP Tasking Examples', 'OpenMP Tasking Cholesky']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - ${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/OpenMP/OpenUH"

OpenMP simple:
  stage: 'Extended Threads Testing'
  needs: ['OpenMP Tasking Examples', 'OpenMP Tasking Cholesky']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - ${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/OpenMP/simple"


## Threads
Threads:
  stage: 'Extended Threads Testing'
  needs: ['Simple Run']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - ${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/Threads"

Thread Based:
  stage: 'Additional Testing'
  needs: ['Simple Run']
  extends: ['.load_run_deps']
  before_script:
    - !reference [.prepare_pcvs_benchmark, before_script]
  script: ['${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/MPI/Thread_based"']
  rules:
    - if: '$HAS_PRIVATIZATION == true && $DO_REGULAR_TESTING == true'


# Benchmarks
RMA MT:
  stage: 'Benchmarks'
  needs: ['Lowcomm', 'MPI Simple C', 'MPI Simple Fortran']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - ${PCVS_COMMAND_BENCH} "${GL_PCVS_BENCHMARKS_PATH}/MPI/rma-mt"

MPI OSU:
  stage: 'Benchmarks'
  needs: ['Lowcomm', 'MPI Simple C', 'MPI Simple Fortran']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - ${PCVS_COMMAND_BENCH} "${GL_PCVS_BENCHMARKS_PATH}/performance/OSU" --run-filter MPI


# Applications
Corals:
  stage: 'Applications'
  needs: ['Lowcomm', 'MPI Simple C', 'MPI Simple Fortran', 'OpenMP Tasking Examples', 'OpenMP Tasking Cholesky']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - |
      ${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/applications/Corals/AMG2013"\
                      "${GL_PCVS_BENCHMARKS_PATH}/applications/Corals/UMT2013"\
                      "${GL_PCVS_BENCHMARKS_PATH}/applications/Corals/graph500-2.1.4"\
                      "${GL_PCVS_BENCHMARKS_PATH}/applications/Corals/mcb-20130723"\
                      "${GL_PCVS_BENCHMARKS_PATH}/applications/Corals/neckbone-2.3.4"

Mantevo:
  stage: 'Applications'
  needs: ['Lowcomm', 'MPI Simple C', 'MPI Simple Fortran', 'OpenMP Tasking Examples', 'OpenMP Tasking Cholesky']
  extends: ['.load_run_deps', '.prepare_pcvs_benchmark']
  script:
    - |
      ${PCVS_COMMAND} "${GL_PCVS_BENCHMARKS_PATH}/applications/Mantevo/CloverLeaf-master"\
                      "${GL_PCVS_BENCHMARKS_PATH}/applications/Mantevo/HPCG-master"\
                      "${GL_PCVS_BENCHMARKS_PATH}/applications/Mantevo/miniAMR-master"\
                      "${GL_PCVS_BENCHMARKS_PATH}/applications/Mantevo/miniGhost-1.0.1"


############################################
############## Finalization ################
############################################

Resources Relinquishing:
  stage: '.post'
  after_script:
    - rm -rf ${GL_LOCAL_INSTALL_DIR} ${GL_LOCAL_BUILD_DIR}
