# This file is the entry point of the testing pipeline
# It prepares the environment then launch the build and run child pipelines
# It also handles side tasks such as linting and doc compilation
---
############################################
############ Pipeline defaults #############
############################################

# Common variables and scripts
include:
  local: '/.gitlab/ci/global.yml'

# Explicit stage definition
stages:
 - Extra Steps
 - Build & Run
 - Build Only

# Default variables. Those with description are intended to be modified manually
variables:
  # mpc-ci path
  GL_MPC_CI_PATH: '$CI_BUILDS_DIR/mpc-ci'
  # pcvs-benchmarks path
  GL_PCVS_BENCHMARKS_PATH: '$CI_BUILDS_DIR/pcvs-benchmarks'
  # Installation option used by all configuration
  GL_INSTALL_COMMON_OPTS: --relwithdebinfo --with-pmix -j32
  # Default pipeline name for the workflow
  GL_PIPELINE_NAME: 'Manually launched on $CI_COMMIT_BRANCH'
  # Enable the extended CI testings
  EXTENDED:
    value: 'false'
    description: 'Activate the extended tests using PCVS-Benchmarks'
    options: ['true', 'false']
  # Enable testing of the --disable-mpcalloc configuration
  EXTRA_CONFIGURATION_TEST_DISABLE_MPCALLOC:
    value: 'false'
    description: 'Activate the tests of the configuration without MPCAlloc'
    options: ['true', 'false']
  # mpc-ci branch
  CI_BRANCH:
    value: 'master'
    description: 'Branch of mpc_ci to use for testing'
  # PCVS-Benchmarks branch
  BENCHMARKS_BRANCH:
    value: 'devel'
    description: 'Branch of pcvs-benchmarks to use for testing in extended mode'


# Pipeline launching rules
workflow:
  name: '$GL_PIPELINE_NAME'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $EXTENDED == "true"'
      variables:
        GL_PIPELINE_NAME: 'Manually launched on $CI_COMMIT_BRANCH (extended)'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      variables:
        EXTENDED: 'true'
        GL_PIPELINE_NAME: 'Scheduled pipeline: extended test suite'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ "/CI::Extended/"'
      variables:
        EXTENDED: 'true'
        GL_PIPELINE_NAME: '$CI_MERGE_REQUEST_TITLE (extended)'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        GL_PIPELINE_NAME: '$CI_MERGE_REQUEST_TITLE'


############################################
################## Setup ###################
############################################

Env Sanitize:
  stage: '.pre'
  needs: []
  script:
    - echo $CI_BUILDS_DIR
    - rm -rf $CI_BUILDS_DIR/*
    - ln -snf "$(ccc_home -u mpc)"/mpc_deps "${HOME}"/.mpcdep

Retrieve Tests:
  stage: '.pre'
  needs: ['Env Sanitize']
  script:
    - echo "Using CI branch ${CI_BRANCH}"
    - |
      if [ ! -d ${GL_MPC_CI_PATH} ]; then
        git clone  --depth 1 -b "${CI_BRANCH}" "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ccc.ocre.cea.fr/cea-mpc-team/mpc-ci.git" ${GL_MPC_CI_PATH}
      fi

Retrieve Benchmarks:
  stage: '.pre'
  needs: ['Env Sanitize']
  script:
    - echo "${BENCHMARKS_BRANCH}"
    - |
      if [ ! -d ${GL_PCVS_BENCHMARKS_PATH} ]; then
        git clone --branch "${BENCHMARKS_BRANCH}" --depth 1 "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ccc.ocre.cea.fr/cea-mpc-team/pcvs-benchmarks.git" "${GL_PCVS_BENCHMARKS_PATH}"
      fi
  rules:
    - if: '$EXTENDED == "true"'



############################################
####### Build & Test configurations ########
############################################

.build_and_run:
  needs: ['Env Sanitize']
  variables:
    CHILD_PIPELINE_NAME: '${CI_JOB_NAME}'
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    strategy: 'mirror'
    include: '/.gitlab/ci/build-and-run.yml'
    forward:
      pipeline_variables: true

.build_only:
  extends: ['.build_and_run']
  stage: 'Build Only'
  variables:
    DO_REGULAR_TESTING: false
  # NOTE: We want the build and run builds to start first to avoid contention
  # start_in does not seem to be supported by out GitLab instance...

Process Mode:
  stage: 'Build & Run'
  extends: ['.build_and_run']
  variables:
    GL_INSTALL_OPTS: '${GL_INSTALL_COMMON_OPTS} --process-mode --disable-spack'
    DO_REGULAR_TESTING: true
    HAS_PRIVATIZATION: false
    HAS_MPI: true

Privatization:
  stage: 'Build & Run'
  extends: ['.build_and_run']
  variables:
    GL_INSTALL_OPTS: '${GL_INSTALL_COMMON_OPTS} --disable-spack'
    DO_REGULAR_TESTING: true
    HAS_PRIVATIZATION: true
    HAS_MPI: true

No MPCAlloc:
  stage: 'Build & Run'
  extends: ['.build_and_run']
  variables:
    GL_INSTALL_OPTS: '${GL_INSTALL_COMMON_OPTS} --disable-spack --disable-mpcalloc'
    DO_REGULAR_TESTING: true
    HAS_PRIVATIZATION: true
    HAS_MPI: true
  rules:
    - if: '$EXTRA_CONFIGURATION_TEST_DISABLE_MPCALLOC == "true"'

Without Lowcomm:
  extends: ['.build_only']
  variables:
    GL_INSTALL_OPTS: '${GL_INSTALL_COMMON_OPTS} --process-mode --mpc-option="--disable-lowcomm"'
    HAS_PRIVATIZATION: false
    HAS_MPI: false

Without MPI:
  extends: ['.build_only']
  variables:
    GL_INSTALL_OPTS: '${GL_INSTALL_COMMON_OPTS} --process-mode --mpc-option="--disable-mpi"'
    HAS_PRIVATIZATION: false
    HAS_MPI: false

Without Threads:
  stage: 'Build Only'
  extends: ['.build_only']
  variables:
    GL_INSTALL_OPTS: '${GL_INSTALL_COMMON_OPTS} --process-mode --mpc-option="--disable-threads"'
    HAS_PRIVATIZATION: false
    HAS_MPI: true

Without PMIx:
  stage: 'Build Only'
  extends: ['.build_only']
  variables:
    GL_INSTALL_OPTS: '--process-mode --relwithdebinfo -j32'
    HAS_PRIVATIZATION: false
    HAS_MPI: true

Without MPCAlloc:
  extends: ['.build_only']
  variables:
    GL_INSTALL_OPTS: '${GL_INSTALL_COMMON_OPTS} --disable-mpcalloc'
    HAS_PRIVATIZATION: true
    HAS_MPI: true
  rules:
    - if: '$EXTRA_CONFIGURATION_TEST_DISABLE_MPCALLOC == "false"'

# FIXME: We have to update Workshare for this test to pass
# Workshare:
#   extends: ['.build_only']
#   variables:
#     GL_INSTALL_OPTS: --enable-workshare --relwithdebinfo -j32
#     HAS_PRIVATIZATION: true
#     HAS_MPI: true
#   allow_failure: true


############################################
####### Pre-commit and documentation #######
############################################

Check Precommit Rules:
  stage: 'Extra Steps'
  needs: ['Env Sanitize']
  before_script:
    - !reference ['.load_pcvs', before_script]
    - export PATH=$PATH:"$(ccc_home -u mpc)/mpc_pre_commit/bin"
  script:
    - cd ${CI_PROJECT_DIR}
    - intify_pre_commit.sh .pre-commit-config.yaml
    - git add .pre-commit-config.yaml
    - spack load py-ruamel-yaml
    - git config --global --add safe.directory "$(ccc_home -u mpc)/mpc_pre_commit/pre_commit_hooks/pre-commit-hooks/.git"
    - git config --global --add safe.directory "$(ccc_home -u mpc)/mpc_pre_commit/pre_commit_hooks/pocc/.git"
    - pre-commit install --install-hooks
    # FIXME: Do not run the clang-tidy hook as it needs a compile_commands.json
    - pre-commit run --all-files --hook-stage manual


############################################
############### Finalization ###############
############################################

Resource Relinquishing:
  stage: '.post'
  when: 'always'
  script:
    - echo "Suppressing ${CI_BUILDS_DIR} data"
  after_script:
    - rm -rf ${CI_BUILDS_DIR}/*
